name: CI

on: [push, pull_request_target]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Ruby 
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install dependencies
        run: gem install awesome_bot
      - name: Run tests
        run: |
          awesome_bot README.md --white-list https://awesome.re,https://github.com/vertica/awesome-vertica,https://www.vertica.com/docs/latest/HTML/Content/Home.htm,www.dbvis.com,community.hitachivantara.com
