name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Ruby 
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: gem install awesome_bot
      - name: Run tests
        run: |
          awesome_bot README.md --white-list https://awesome.re,https://github.com/vertica/awesome-vertica,https://www.vertica.com/docs/latest/HTML/Content/Home.htm,community.jaspersoft.com,community.hitachivantara.com
